In [1]:
import pandas as pd

In [2]:
bikes= pd.read_csv(r'C:\Users\hp\Downloads\london_merged.csv')
bikes

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0
5,2015-01-04 05:00:00,46,2.0,2.0,93.0,4.0,1.0,0.0,1.0,3.0
6,2015-01-04 06:00:00,51,1.0,-1.0,100.0,7.0,4.0,0.0,1.0,3.0
7,2015-01-04 07:00:00,75,1.0,-1.0,100.0,7.0,4.0,0.0,1.0,3.0
8,2015-01-04 08:00:00,131,1.5,-1.0,96.5,8.0,4.0,0.0,1.0,3.0
9,2015-01-04 09:00:00,301,2.0,-0.5,100.0,9.0,3.0,0.0,1.0,3.0
10,2015-01-04 10:00:00,528,3.0,-0.5,93.0,12.0,3.0,0.0,1.0,3.0
11,2015-01-04 11:00:00,727,2.0,-1.5,100.0,12.0,3.0,0.0,1.0,3.0
12,2015-01-04 12:00:00,862,2.0,-1.5,96.5,13.0,4.0,0.0,1.0,3.0
13,2015-01-04 13:00:00,916,3.0,-0.5,87.0,15.0,3.0,0.0,1.0,3.0
14,2015-01-04 14:00:00,1039,2.5,0.0,90.0,8.0,3.0,0.0,1.0,3.0
15,2015-01-04 15:00:00,869,2.0,-1.5,93.0,11.0,3.0,0.0,1.0,3.0
16,2015-01-04 16:00:00,737,3.0,0.0,93.0,12.0,3.0,0.0,1.0,3.0
17,2015-01-04 17:00:00,594,3.0,0.0,93.0,11.0,3.0,0.0,1.0,3.0
18,2015-01-04 18:00:00,522,3.0,1.5,93.0,6.5,3.0,0.0,1.0,3.0
19,2015-01-04 19:00:00,379,3.0,1.0,93.0,7.0,3.0,0.0,1.0,3.0
20,2015-01-04 20:00:00,328,3.0,3.0,93.0,4.0,3.0,0.0,1.0,3.0
21,2015-01-04 21:00:00,221,3.0,2.5,93.0,5.0,4.0,0.0,1.0,3.0
22,2015-01-04 22:00:00,178,3.0,2.0,93.0,6.0,4.0,0.0,1.0,3.0
23,2015-01-04 23:00:00,157,4.0,3.5,87.0,5.0,4.0,0.0,1.0,3.0
24,2015-01-05 00:00:00,83,4.0,3.0,93.0,6.0,4.0,0.0,0.0,3.0
25,2015-01-05 01:00:00,67,4.0,3.5,93.0,5.0,4.0,0.0,0.0,3.0
26,2015-01-05 02:00:00,32,5.0,4.0,87.0,6.0,4.0,0.0,0.0,3.0
27,2015-01-05 03:00:00,22,6.0,4.5,84.0,7.5,4.0,0.0,0.0,3.0
28,2015-01-05 04:00:00,38,6.5,5.0,84.0,8.0,4.0,0.0,0.0,3.0
29,2015-01-05 05:00:00,81,6.0,5.5,87.0,5.0,4.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...
17384,2017-01-02 18:00:00,594,3.0,0.0,84.0,9.0,1.0,1.0,0.0,3.0
17385,2017-01-02 19:00:00,433,3.0,0.0,81.0,11.0,1.0,1.0,0.0,3.0
17386,2017-01-02 20:00:00,334,3.0,0.0,75.0,13.0,1.0,1.0,0.0,3.0
17387,2017-01-02 21:00:00,233,2.5,-0.5,78.0,11.0,1.0,1.0,0.0,3.0
17388,2017-01-02 22:00:00,201,2.0,-1.0,81.0,10.0,1.0,1.0,0.0,3.0
17389,2017-01-02 23:00:00,145,1.0,-2.0,93.0,10.0,1.0,1.0,0.0,3.0
17390,2017-01-03 00:00:00,63,1.0,-2.0,90.0,11.0,1.0,0.0,0.0,3.0
17391,2017-01-03 01:00:00,49,1.0,-2.0,87.0,10.0,1.0,0.0,0.0,3.0
17392,2017-01-03 02:00:00,43,0.5,-3.0,90.0,11.0,1.0,0.0,0.0,3.0
17393,2017-01-03 03:00:00,10,0.0,-4.0,93.0,13.0,1.0,0.0,0.0,3.0
17394,2017-01-03 04:00:00,30,0.0,-4.0,93.0,14.0,1.0,0.0,0.0,3.0
17395,2017-01-03 05:00:00,83,0.5,-3.5,90.0,14.0,3.0,0.0,0.0,3.0
17396,2017-01-03 06:00:00,434,1.0,-3.5,87.0,18.0,1.0,0.0,0.0,3.0
17397,2017-01-03 07:00:00,1407,1.0,-4.0,87.0,19.0,1.0,0.0,0.0,3.0
17398,2017-01-03 08:00:00,2904,1.0,-3.5,87.0,18.5,3.0,0.0,0.0,3.0
17399,2017-01-03 09:00:00,1357,2.5,-1.5,81.0,14.0,1.0,0.0,0.0,3.0
17400,2017-01-03 10:00:00,661,3.0,-2.0,81.0,20.0,1.0,0.0,0.0,3.0
17401,2017-01-03 11:00:00,636,4.0,0.0,78.0,21.0,1.0,0.0,0.0,3.0
17402,2017-01-03 12:00:00,825,5.0,1.0,76.0,21.0,3.0,0.0,0.0,3.0
17403,2017-01-03 13:00:00,878,6.0,2.0,71.0,23.0,4.0,0.0,0.0,3.0
17404,2017-01-03 14:00:00,765,6.0,2.0,73.5,22.0,3.0,0.0,0.0,3.0
17405,2017-01-03 15:00:00,845,6.0,2.0,71.0,27.0,4.0,0.0,0.0,3.0
17406,2017-01-03 16:00:00,1201,6.0,2.0,71.0,26.0,4.0,0.0,0.0,3.0
17407,2017-01-03 17:00:00,2742,6.0,2.0,73.5,21.0,3.0,0.0,0.0,3.0
17408,2017-01-03 18:00:00,2220,5.0,1.0,81.0,22.0,2.0,0.0,0.0,3.0
17409,2017-01-03 19:00:00,1042,5.0,1.0,81.0,19.0,3.0,0.0,0.0,3.0
17410,2017-01-03 20:00:00,541,5.0,1.0,81.0,21.0,4.0,0.0,0.0,3.0
17411,2017-01-03 21:00:00,337,5.5,1.5,78.5,24.0,4.0,0.0,0.0,3.0
17412,2017-01-03 22:00:00,224,5.5,1.5,76.0,23.0,4.0,0.0,0.0,3.0
17413,2017-01-03 23:00:00,139,5.0,1.0,76.0,22.0,2.0,0.0,0.0,3.0

In [3]:
bikes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
timestamp       17414 non-null object
cnt             17414 non-null int64
t1              17414 non-null float64
t2              17414 non-null float64
hum             17414 non-null float64
wind_speed      17414 non-null float64
weather_code    17414 non-null float64
is_holiday      17414 non-null float64
is_weekend      17414 non-null float64
season          17414 non-null float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB

In [4]:
bikes.shape

(17414, 10)

In [6]:
bikes['weather_code'].value_counts()

1.0     6150
2.0     4034
3.0     3551
7.0     2141
4.0     1464
26.0      60
10.0      14
Name: weather_code, dtype: int64

In [9]:
#Renamimg the columns 
new_columns = {
    'timestamp':'time',
    'cnt':'count',
    't1':'temperature_real',
    't2':'temperature_feels',
    'hum': 'humidity_percent',
    'wind_speed': 'wind_speed_kph',
    'weather_code':'weather',
    'is_holiday': 'is_holiday',
    'is_weekend': 'is_weekend',
    'season':'season' 
}
bikes.rename(new_columns, axis=1, inplace=True)

In [10]:
bikes.head(5)

,time,count,temperature_real,temperature_feels,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [11]:
#Changing humidity values to percentage
bikes['humidity_percent'] = bikes['humidity_percent'] / 100

In [14]:
# creating a season dictionary to map the integers 0-3 to the actual written values 
season_dict= {
    '0.0':'Spring',
    '1.0': 'Summer',
    '2.0': 'Autumn',
    '3.0': 'Winter'
}

#changing the season column datatype to string
bikes['season']= bikes['season'].astype('str')

#mapping the integer to the actual written values 
bikes['season']= bikes['season'].map(season_dict)

In [15]:
# creating a weather dictionary to map the integers  to the actual written values 
weather_dict ={
    '1.0':'Clear',
    '2.0':'Scattered clouds',
    '3.0': 'Broken clouds',
    '4.0': 'Cloudy',
    '7.0': 'Rain',
    '10.0': 'Rain with thunderstorm',
    '26.0': 'Snowfall'
}

#changing the weather column datatype to string
bikes['weather']= bikes['weather'].astype('str')

#mapping the integer to the actual written weather 
bikes['weather']= bikes['weather'].map(weather_dict)

In [17]:
#checking the dataframe to see if the mappingd worked 
bikes.head(5)

,time,count,temperature_real,temperature_feels,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Broken clouds,0.0,1.0,Winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clear,0.0,1.0,Winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clear,0.0,1.0,Winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clear,0.0,1.0,Winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clear,0.0,1.0,Winter

In [19]:
bikes.to_excel(r'C:\Users\hp\Downloads\london_bikes_final.xlsx', sheet_name= 'Data')